# Generated by Django 3.0.6 on 2020-07-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='motto',
            field=models.CharField(default='Lisää mottosi tähän', max_length=500),
        ),
    ]
