# Generated by Django 3.0.6 on 2020-07-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_motto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='motto',
            field=models.TextField(default='Lisää mottosi tähän', max_length=500),
        ),
    ]
