# Generated by Django 3.0.6 on 2020-07-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_ohje_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ohje',
            name='dish',
        ),
    ]
